[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"
  PNPM_FLAGS = "--shamefully-hoist"

[dev]
  command = "pnpm dev"
  targetPort = 3000
