<script setup lang="ts">
import { capabilities, systemModules } from '~/data/company'
import { industries } from '~/data/industries'
import { platforms } from '~/data/platforms'
import { partnerRequirements, unsuitable } from '~/data/partners'
usePageSeo('全球品牌联营平台','行星跨境通过全球品牌联营模式，帮助优秀制造企业连接全球消费市场，共同打造国际竞争力品牌。')
const flow = ['制造企业','产品研发','品牌共建','全球渠道','市场销售','利润共享']
</script>
<template>
  <main>
    <HeroSection />
    <section class="section-pad bg-[#F7F8FA]">
      <div class="container-shell"><div class="mb-14 grid gap-8 lg:grid-cols-2"><div><div class="eyebrow">WHO WE ARE</div><h2 class="section-title mt-5">我们不是采购商<br>而是品牌共建伙伴</h2></div><p class="section-copy self-end">行星跨境是一家专注全球中高端家居品牌孵化与联营的跨境电商运营平台。我们整合全球供应链、全球渠道、品牌运营与数字化能力，帮助制造企业从产品制造走向品牌创造。</p></div><FeatureCards :items="capabilities" /></div>
    </section>
    <section class="section-pad">
      <div class="container-shell"><div class="text-center"><div class="eyebrow">A NEW PARTNERSHIP</div><h2 class="section-title mt-5">从供应关系，到品牌共同成长</h2></div><div class="mx-auto mt-14 grid max-w-5xl gap-5 md:grid-cols-2"><div class="rounded-3xl bg-[#F2F4F6] p-9"><div class="text-xs tracking-[.2em] text-slate-400">传统模式</div><h3 class="mt-4 text-2xl font-semibold text-slate-500">一次性供应关系</h3><ul class="mt-8 space-y-4 text-slate-500"><li v-for="x in ['OEM生产','价格竞争','利润有限','缺少品牌资产']" :key="x" class="flex items-center gap-3"><span class="text-slate-300">—</span>{{ x }}</li></ul></div><div class="rounded-3xl bg-[#0B1F33] p-9 text-white shadow-2xl"><div class="text-xs tracking-[.2em] text-[#C9A86A]">品牌联营模式</div><h3 class="mt-4 text-2xl font-semibold">长期价值共同体</h3><ul class="mt-8 space-y-4"><li v-for="x in ['产品共创','全球运营','利润共享','长期合作']" :key="x" class="flex items-center gap-3 text-white/75"><span class="text-[#C9A86A]">✓</span>{{ x }}</li></ul></div></div></div>
    </section>
    <section class="section-pad bg-[#F7F8FA]"><div class="container-shell"><div class="max-w-3xl"><div class="eyebrow">WHO WE HELP</div><h2 class="section-title mt-5">寻找共同打造全球品牌的制造伙伴</h2></div><div class="mt-14 grid gap-5 md:grid-cols-2"><IndustryCard v-for="item in industries" :key="item.name" :item="item" /></div></div></section>
    <section class="section-pad overflow-hidden bg-[#0B1F33] text-white"><div class="container-shell"><div class="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><div class="eyebrow text-[#C9A86A]">PARTNERSHIP MODEL</div><h2 class="mt-5 text-4xl font-semibold tracking-tight md:text-5xl">全球品牌联营模式</h2><p class="mt-6 leading-8 text-white/52">双方资源共享、优势互补、利益绑定，共同经营产品项目与品牌资产。</p></div><div class="grid gap-6 md:grid-cols-2"><div class="rounded-2xl border border-white/10 p-7"><span class="text-xs text-[#C9A86A]">制造企业负责</span><div class="mt-5 grid grid-cols-2 gap-3 text-sm text-white/70"><span v-for="x in ['产品研发','生产制造','品质管理','供应链保障']" :key="x">{{ x }}</span></div></div><div class="rounded-2xl border border-[#C9A86A]/30 bg-[#C9A86A]/5 p-7"><span class="text-xs text-[#C9A86A]">行星跨境负责</span><div class="mt-5 grid grid-cols-2 gap-3 text-sm text-white/70"><span v-for="x in ['市场研究','品牌建设','全球销售','广告营销','海外仓储','客户服务']" :key="x">{{ x }}</span></div></div></div></div><div class="mt-14 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-9"><template v-for="(x,i) in flow" :key="x"><span class="rounded-full border border-white/15 px-5 py-3 text-sm">{{ x }}</span><span v-if="i<flow.length-1" class="text-[#C9A86A]">→</span></template></div></div></section>
    <section class="section-pad"><div class="container-shell"><div class="text-center"><div class="eyebrow">PGBOS</div><h2 class="section-title mt-5">完整的全球品牌运营系统</h2><p class="section-copy mx-auto mt-5 max-w-2xl">贯穿市场研究、产品研发、品牌建设、全球销售与持续迭代的全生命周期。</p></div><div class="relative mx-auto mt-14 max-w-4xl"><div class="grid grid-cols-2 gap-4 md:grid-cols-4"><div v-for="(m,i) in systemModules" :key="m[0]" class="group aspect-square rounded-full border border-slate-200 bg-white p-5 text-center shadow-sm transition hover:border-[#C9A86A] hover:shadow-xl"><div class="grid h-full place-content-center"><span class="text-xs text-[#B28D4D]">0{{ i+1 }}</span><b class="mt-2 text-base text-[#0B1F33]">{{ m[0] }}</b><small class="mt-1 text-[9px] tracking-widest text-slate-400">{{ m[1] }}</small></div></div></div></div></div></section>
    <section class="section-pad bg-[#0B1F33] text-white"><div class="container-shell"><div class="grid gap-10 lg:grid-cols-2"><div><div class="eyebrow text-[#C9A86A]">GLOBAL CHANNELS</div><h2 class="mt-5 text-4xl font-semibold md:text-5xl">覆盖全球主流消费市场</h2><p class="mt-6 max-w-lg leading-8 text-white/50">坚持多平台、多国家、多渠道布局，不依赖单一流量入口。</p><div class="mt-9 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 md:grid-cols-4"><div v-for="p in platforms" :key="p" class="grid h-20 place-items-center bg-[#0B1F33] text-sm text-white/65">{{ p }}</div></div></div><GlobalMap /></div></div></section>
    <section class="section-pad"><div class="container-shell"><div class="text-center"><div class="eyebrow">CATEGORY STRATEGY</div><h2 class="section-title mt-5">从单一产品，到全球生活空间品牌</h2></div><div class="mt-14 grid gap-4 md:grid-cols-5"><div v-for="(x,i) in ['镜类空间','室内家具','卫浴空间','户外生活','厨房空间']" :key="x" class="card p-6"><span class="text-xs text-[#C9A86A]">0{{ i+1 }}</span><h3 class="mt-12 text-lg font-semibold text-[#0B1F33]">{{ x }}</h3></div></div></div></section>
    <section class="section-pad bg-[#F7F8FA]"><div class="container-shell grid gap-10 lg:grid-cols-2"><div><div class="eyebrow">PARTNER STANDARD</div><h2 class="section-title mt-5">我们寻找长期战略伙伴</h2><div class="mt-9 grid grid-cols-2 gap-3"><div v-for="x in partnerRequirements" :key="x" class="rounded-xl bg-white p-4 text-sm text-[#0B1F33] shadow-sm"><span class="mr-2 text-[#B28D4D]">✓</span>{{ x }}</div></div></div><div class="rounded-3xl bg-white p-8 shadow-sm"><span class="text-xs tracking-widest text-slate-400">暂不适合</span><div class="mt-5 space-y-4"><div v-for="x in unsuitable" :key="x" class="border-b border-slate-100 pb-4 text-sm text-slate-500">— {{ x }}</div></div><p class="mt-6 text-sm leading-7 text-slate-400">我们更期待与年销售规模 5000 万元以上、具备持续发展能力的制造企业合作。</p></div></div></section>
    <section class="section-pad"><div class="container-shell"><div class="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><div class="eyebrow">GROWTH CASE</div><h2 class="section-title mt-5">优秀制造企业<br>全球增长案例</h2></div><div class="card overflow-hidden"><div class="grid md:grid-cols-2"><div class="p-8"><small class="text-slate-400">合作前</small><h3 class="mt-3 text-xl font-semibold text-[#0B1F33]">广东某大型制造企业</h3><p class="mt-4 text-sm leading-7 text-slate-500">以 OEM 与传统外贸为主，年销售规模约 2 亿元，缺少跨境品牌运营经验。</p></div><div class="bg-[#0B1F33] p-8 text-white"><small class="text-[#C9A86A]">合作后</small><div class="mt-5 flex flex-wrap gap-2"><span v-for="x in ['Amazon','Wayfair','Walmart','Home Depot',`Lowe's`]" :key="x" class="rounded-full border border-white/15 px-3 py-1 text-xs">{{ x }}</span></div><div class="mt-8 grid grid-cols-2 gap-5"><div><b class="text-3xl text-[#D7BC83]">2亿+</b><small class="block text-white/40">2025销售额</small></div><div><b class="text-3xl text-[#D7BC83]">15–20%</b><small class="block text-white/40">平均利润率</small></div></div></div></div></div></div></div></section>
    <section id="apply" class="section-pad bg-[#F7F8FA]"><div class="container-shell grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><div class="eyebrow">START A PARTNERSHIP</div><h2 class="section-title mt-5">成为全球品牌<br>共建伙伴</h2><p class="section-copy mt-6">如果您拥有真实制造能力、研发优势与长期品牌愿景，我们期待与您建立联系。</p></div><div class="card p-7 md:p-10"><PartnerForm /></div></div></section>
  </main>
</template>
